/**:
  ros__parameters:
    target_ip: "192.168.6.101"
    streamer_ip: "192.168.6.100"
    target_port_rgb: 8081
    target_port_depth: 8083
    target_port_ir: 8085
    target_port_metadata: 8091
    
    # Right Camera Device ID
    device_id: "230422271116"

    # Which streams to enable
    enable_rgb: false
    enable_depth: true
    enable_ir: true

    # RGB settings (Ignored since enable_rgb is false)
    rgb_width: 640
    rgb_height: 480
    rgb_format: "RGB8"
    rgb_fps: 15

    # Depth settings (480x270 fits USB 2.0 bandwidth at 30fps)
    depth_width: 480
    depth_height: 270
    depth_format: "Z16"
    depth_fps: 30

    # IR settings (480x270 fits USB 2.0 bandwidth at 30fps)
    ir_width: 480
    ir_height: 270
    ir_format: "Y8"
    ir_fps: 30
